import { OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { AlertService } from '../@core/service/alert.service';
import { ConfirmationService } from 'primeng/api';
import { EmailTemplateService } from '../@core/service/email-template.service';
import { RBACINFO } from '../@core/urls/email-template-url.config';
import { Subscription } from 'rxjs';
import { DataStoreService } from '../@core/service/data-store.service';
import * as i0 from "@angular/core";
export declare class EmailComponent implements OnInit {
    private _emailTemplateService;
    private _alertService;
    private formBuilder;
    private confirmationService;
    private _storeservice;
    emailTemplateForm: FormGroup;
    editTemplateId: string;
    editStatus: boolean;
    currentUser: any;
    templateList: any;
    editor: any;
    totalNotificationCount: number;
    allEmailTemplateCategories: any;
    generateTemplate: any;
    templatevaliableList: any;
    environment: any;
    RBACORG: RBACINFO;
    PERMISSION: any;
    orgSubs: Subscription;
    orgId: any;
    constructor(_emailTemplateService: EmailTemplateService, _alertService: AlertService, formBuilder: FormBuilder, confirmationService: ConfirmationService, _storeservice: DataStoreService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    formInitialize(): void;
    editTemplate(templateinfo: any): void;
    saveTemplate(): any;
    updateTemplate(status: any): any;
    genericTemplate(modal: any, status: any): void;
    reset(): void;
    initEditor(): void;
    editorInit(): void;
    getAllEmailTemplateCategories(): void;
    getEmailTemplateList(): void;
    deleteTemplate(): void;
    validateTemplateCreate(): void;
    validateTempUpdate(): void;
    copyText(val: string): void;
    getVariableList(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EmailComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EmailComponent, "pics-email", never, {}, {}, never, never>;
}
